name: dbt Build on Push

on:
  push:
    branches:
      - main

jobs:
  dbt_build:
    name: Run dbt build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt and adapter
        run: |
          pip install dbt-snowflake

      - name: Set up dbt profile
        env:
          DBT_SNOWFLAKE_USER: ${{ secrets.DBT_SNOWFLAKE_USER }}
          DBT_SNOWFLAKE_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PASSWORD }}
          DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
          DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE }}
          DBT_SNOWFLAKE_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_WAREHOUSE }}
          DBT_SNOWFLAKE_DATABASE: ${{ secrets.DBT_SNOWFLAKE_DATABASE }}
          DBT_SNOWFLAKE_SCHEMA: ${{ secrets.DBT_SNOWFLAKE_SCHEMA }}
        run: |
          mkdir -p ~/.dbt
          echo "
          dbt_taxi_project:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: \"$DBT_SNOWFLAKE_ACCOUNT\"
                user: \"$DBT_SNOWFLAKE_USER\"
                password: \"$DBT_SNOWFLAKE_PASSWORD\"
                role: \"$DBT_SNOWFLAKE_ROLE\"
                warehouse: \"$DBT_SNOWFLAKE_WAREHOUSE\"
                database: \"$DBT_SNOWFLAKE_DATABASE\"
                schema: \"$DBT_SNOWFLAKE_SCHEMA\"
                threads: 4
          " > ~/.dbt/profiles.yml

      - name: Run dbt build
        run: dbt build --project-dir ./dbt_taxi_project
